Difficultés rencontrées
-----------------------

Execution TP: 
	- Utiliser environement Base38
	- Lancer une console anaconda
	- se diriger dans le repertoire de travail
		 D:\_Intelligence Artificielle\10 - 420-A61-Préparation solution IA mise en place\TP1\A61-TP1\packages\regression_model
	- lancer tox

Partie 3
--------
Objectif
	- Ajout des prédictions

Probleme 
	- WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
		Partir de Python 3.8.10 mon env était en 3.8.18
		$ conda create -n base38 python==3.8.10

	- TypeError: expected str, bytes or os.PathLike object, not NoneType
    		Nécessite l'ajout de fichier vide __init__.py dans les repertoire python
	
	- Probleme chemin trop long
	    https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later
	    J'ai du activer le long path de windows 

Partie 4
--------
Objectif
	- Ajouter les validation des données d'entrées
	- Nouveau test avec prediction multiple

Partie 5
--------
Objectif 
	- Ajout des feature engine au pipeline
		- Log tranformer 
	- On a isoler les feature engine dans son propre fichier

Partie 6
--------
Objectif 
	- Ajout d'un module de log

Partie 7
--------
Objectif 
	- Creation d'un package
	- Ce package sera installable avec pip incluant tous les requis
	- Ceci permettra d'importer notre librairie directement dans python

Partie 8
--------
Objectif
	- Configuration du Rest-API flask

Probleme
	- Installation des requirements de ml-api
		ERROR: C:\Users\Dell\Desktop\cours-A61\cours-A61\packages\regression_model is not a valid editable requirement
			- Il faut changer le path pour mon path local dans le nouveau fichier requirements.txt
			 e "D:\_Intelligence Artificielle\10 - 420-A61-Préparation solution IA mise en plac\TP1\A61-TP1\packages\regression_model"
			Cependant j'obtenais une erreur de path invalide j'ai donc changé la ligne pour installer le package de la facon suivant
				regression_model>=0.0.0

	- Execution de run.py
		ERROR: ImportError: cannot import name 'Markup' from 'jinja2' 
			- j'ai désinstaller Flask et jinja2 puis réinstallé ce qui a réglé le probleme


Partie 9 
--------
Objectif
	- Ajout config, log et test a Flask api

Partie 10
---------
Objectif
	- Ajout partie prediction a Flask API

	***** ATTENTION MODIF requirements.txt dans ml_api il ne faut pas écraser les modifs précédentes sur mon répertoire local*****

Partie 11
---------
Objectif
	- Ajout de version a notre application flask

	- Erreur obtenu lors du lancement des tests
		(base38) D:\_Intelligence Artificielle\10 - 420-A61-Préparation solution IA mise en place\TP1\A61-TP1\packages\ml_api>python run.py
		Error processing line 1 of C:\Users\Josee\.conda\envs\base38\lib\site-packages\distutils-precedence.pth:

	 	Traceback (most recent call last):
		    File "C:\Users\Josee\.conda\envs\base38\lib\site.py", line 169, in addpackage
		      exec(line)
		    File "<string>", line 1, in <module>
		  ModuleNotFoundError: No module named '_distutils_hack'

	- Pour corriger l'erreur j'ai mis a jour le setup tools
		python.exe -m pip install -U pip setuptools
		pip install -U pip setuptools

